version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - server-db
    environment:
      PORT: 8000
      DB_HOST: server-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: server
      SECRET_KEY: secret123

  server-db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
  proxy:
    image: nginx
    depends_on:
      - server
    ports:
      - 8070:8070
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/service.conf

volumes:
  db: